site_name: FUSE manual
repo_url: https://github.com/CH-Earth/fuse
site_url: https://ch-earth.github.io/fuse/
edit_uri: edit/develop/docs/
docs_dir: docs

theme:
  name: readthedocs
  nav_style: dark

nav:
  - Home: index.md

  - Getting Started:
      - Installation: 'install/install_fuse.md'
      - Quick Start: 'install/test_cases.md'
      - Preparing Input Data for FUSE: 'install/test_data.md'

  - User Guide:
      - Running FUSE:
          - Overview: 'modes/overview.md'
          - Command-line arguments: 'modes/arguments.md'
          - Execution modes: 'modes/execution_modes.md'
          - Spatial modes: 'modes/spatial_modes.md'
          - Numerical methods: 'modes/numerical_methods.md'
      - Model configuration:
          - Model structure: 'modes/structure.md'
      - Input and output:
          - File manager: 'files/file_manager.md'
          - Input files: 'files/input_files.md'
          - Settings files: 'files/settings_files.md'
          - Output files: 'files/output_files.md'

  - Process modules:
      - Precipitation: 'modules/1_precip.md'

  - Advanced topics:
      - MPI execution: 'extras/mpi.md'
      - Coupling with mizuRoute: 'extras/mizuRoute.md'
      - Tools for FUSE (TOFU): 'extras/tofu.md'
      - CAMELS for FUSE: 'extras/camels_for_fuse.md'
