site_name: FUSE manual
repo_url: https://github.com/CH-Earth/fuse
site_url: https://ch-earth.github.io/fuse/
edit_uri: edit/develop/docs/
docs_dir: docs

theme:
  name: readthedocs
  nav_style: dark

nav:
  - Home: index.md

  - Getting Started:
      - Installation: 'install/install_fuse.md'
      - Build dependencies: 'install/build_dependencies.md'
      - Running simulations: 'install/test_cases.md'
      - Preparing Input Data for FUSE: 'install/test_data.md'

  - User Guide:
      - Overview: 'modes/overview.md'
      - Simulation setup: 'modes/simulation_setup.md'
      - Spatial configuration: 'modes/spatial_configuration.md'
      - Hydrologic model definition:
          - Overview: 'modes/hydrologic_model.md'
          - Model structure: 'modes/structure.md'
          - Model parameters: 'modes/parameters.md'
          - Numerical methods: 'modes/numerical_methods.md'
      - Model inputs: 'files/input_files.md'
      - Model outputs: 'files/output_files.md'

  - Advanced topics:
      - MPI execution: 'extras/mpi.md'
      - Coupling with mizuRoute: 'extras/mizuRoute.md'
